const volunteerData = [
  {
    id: 1,
    taskName: 'Child support',
    img: 'https://i.ibb.co/wCY7sQh/1.png',
    color: '#ffbd3e',
    date: new Date().toDateString(),
  },
  {
    id: 2,
    taskName: 'Refuge shelter',
    img: 'https://i.ibb.co/cc3431C/2.png',
    color: '#ff7044',
    date: new Date().toDateString(),
  },
  {
    id: 3,
    taskName: 'food Charity',
    img: 'https://i.ibb.co/N7zgsWq/3.png',
    color: '#3f90fc',
    date: new Date().toDateString(),
  },
  {
    id: 4,
    taskName: 'Host a clothing swap',
    img: 'https://i.ibb.co/BsfVZjD/4.png',
    color: '#421fcf',
    date: new Date().toDateString(),
  },
  {
    id: 5,
    taskName: 'Host a rive clean-up',
    img: 'https://i.ibb.co/QYLQFY1/5.png',
    color: '#421fcf',
    date: new Date().toDateString(),
  },
  {
    id: 6,
    taskName: 'Clean water for children',
    img: 'https://i.ibb.co/qWS43h0/6.png',
    color: '#3f90fc',
    date: new Date().toDateString(),
  },
  {
    id: 7,
    taskName: 'Good education',
    img: 'https://i.ibb.co/YLbSVbY/7.png',
    color: '#ff7044',
    date: new Date().toDateString(),
  },
  {
    id: 8,
    taskName: 'New books for children',
    img: 'https://i.ibb.co/RH72LGz/8.png',
    color: '#ffbd3e',
    date: new Date().toDateString(),
  },
  {
    id: 9,
    taskName: 'Host a study group',
    img: 'https://i.ibb.co/3BKDXQM/9.png',
    color: '#ffbd3e',
    date: new Date().toDateString(),
  },
  {
    id: 10,
    taskName: 'Build birdhouses for your neighbors',
    img: 'https://i.ibb.co/hW9SJNY/10.png',
    color: '#ff7044',
    date: new Date().toDateString(),
  },
  {
    id: 11,
    taskName: 'Organize books at the library',
    img: 'https://i.ibb.co/C6xrwXd/11.png',
    color: '#3f90fc',
    date: new Date().toDateString(),
  },
  {
    id: 12,
    taskName: 'Give a seminar on driving safety',
    img: 'https://i.ibb.co/2SCzq0c/12.png',
    color: '#421fcf',
    date: new Date().toDateString(),
  },
  {
    id: 13,
    taskName: 'Give free music lessons',
    img: 'https://i.ibb.co/v4bhjHW/13.png',
    color: '#ffbd3e',
    date: new Date().toDateString(),
  },
  {
    id: 14,
    taskName: 'Tech people how to register to vote',
    img: 'https://i.ibb.co/3y3N13N/14.png',
    color: '#3f90fc',
    date: new Date().toDateString(),
  },
  {
    id: 15,
    taskName: 'Clean up your local park',
    img: 'https://i.ibb.co/JztsCNb/15.png',
    color: '#421fcf',
    date: new Date().toDateString(),
  },
  {
    id: 16,
    taskName: 'Give IT help to local adults',
    img: 'https://i.ibb.co/Lr19fGN/16.png',
    color: '#ff7044',
    date: new Date().toDateString(),
  },
  {
    id: 17,
    taskName: 'Foster a shelter animal',
    img: 'https://i.ibb.co/yhttsYd/17.png',
    color: '#ff7044',
    date: new Date().toDateString(),
  },
  {
    id: 18,
    taskName: 'Babysit during PTA meetings',
    img: 'https://i.ibb.co/23Tszpz/18.png',
    color: '#ffbd3e',
    date: new Date().toDateString(),
  },
  {
    id: 19,
    taskName: 'collect stuffed animals',
    img: 'https://i.ibb.co/pyvCxR5/19.png',
    color: '#3f90fc',
    date: new Date().toDateString(),
  },
  {
    id: 20,
    taskName: 'Collect school supplies',
    img: 'https://i.ibb.co/P6BLfWR/20.png',
    color: '#421fcf',
    date: new Date().toDateString(),
  },
];

export default volunteerData;
